### ISSUE TITLE
Add capability to set the host/TCP port for incoming GRPC connections

### ISSUE THREAD

**Issue by metacoma** [metacoma/freeplane_plugin_grpc#3]
At this moment, the host and port are hardcoded https://github.com/metacoma/freeplane_plugin_grpc/blob/ca8f667a0f373506c579762c92ffd954ca1827c7/src/main/java/org/freeplane/plugin/grpc/GrpcRegistration.java#L59-L65

**Comment by SandboxHead** [comment]
Hey. Do you want the host and port to be in a config file or from the command line argument?

**Comment by metacoma** [comment]
hey @SandboxHead!

It would be great if the gRPC listen address and bind port could be configured using Freeplane command line arguments.

**Comment by metacoma** [comment]
```bash
$ export GRPC_LISTEN_ADDR=0.0.0.0
$ export GRPC_LISTEN_PORT=50053
$ BIN/freeplane.sh
```
